version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:latest
    working_directory: ~/workspace


commands:
  install_module:
    steps:
      - run:
          name: module install
          when: always
          command: npm ci
  restore_npm_cache:
    steps:
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}

jobs:
  module-install:
    executor: default
    steps:
      - checkout
      - install_module
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          when: always
          paths:
            - ~/.npm

  lint:
    executor: default
    steps:
      - checkout
      - restore_npm_cache
      - install_module
      - run:
          name: lint
          command: npm run lint

  build:
    executor: default
    steps:
      - checkout
      - restore_npm_cache
      - install_module
      - run:
          name: gen swagger.d.ts
          command: npm run gen-swagger-type
      - run:
          name: build
          command: npm run build --morden

  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: install utils
          command: npm install --global semver
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build and push
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              IMAGE_TAG="${CIRCLE_TAG:1}"
              latest=`cat <(curl -Ls https://registry.hub.docker.com/v1/repositories/trap/traq-ui/tags | jq -r '.[].name' | grep -E '^[0-9]+(\.[0-9]+){2}.*') <(echo $IMAGE_TAG) | xargs semver | tail -n 1`
              if [ "$IMAGE_TAG" = "$latest" ]; then
                NEW_RELEASE=1
              fi
            elif [ "$CIRCLE_BRANCH" = "master" ]; then
              IMAGE_TAG="latest"
            else
              IMAGE_TAG="$CIRCLE_BRANCH"
            fi
            docker build -t trap/traq-ui:$IMAGE_TAG .
            docker push trap/traq-ui:$IMAGE_TAG

            if [ "$NEW_RELEASE" = "1" ]; then
              docker tag trap/traq-ui:$IMAGE_TAG trap/traq-ui:release
              docker push trap/traq-ui:release
            fi

  deploy-staging:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cd:2f:d4:8c:86:98:63:5e:07:37:78:65:f8:2a:a2:cc"
      - run:
          name: ssh-keyscan
          command: ssh-keyscan ${STAGING_DEPLOY_HOST} >> ~/.ssh/known_hosts 2>/dev/null
      - run:
          name: deploy staging environment
          command: ssh -o LogLevel=QUIET -t ${STAGING_DEPLOY_USER}@${STAGING_DEPLOY_HOST} "~/deploy.sh traq-frontend"

  deploy-prod:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cd:2f:d4:8c:86:98:63:5e:07:37:78:65:f8:2a:a2:cc"
      - run:
          name: ssh-keyscan
          command: ssh-keyscan ${PROD_DEPLOY_HOST} >> ~/.ssh/known_hosts 2>/dev/null
      - run:
          name: deploy production environment
          command: ssh -o LogLevel=QUIET -t ${PROD_DEPLOY_USER}@${PROD_DEPLOY_HOST} "~/deploy.sh traq-frontend"

workflows:
  version: 2
  main:
    jobs:
      - module-install
      - lint:
          requires:
            - module-install
      - build:
          requires:
            - module-install
      - build-image:
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
      - pending-approval:
          type: approval
          requires:
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
      - deploy-staging:
          requires:
            - build-image
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - pending-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
