version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/workspace


commands:
  install_module:
    steps:
      - run:
          name: module install
          when: always
          command: npm ci
  restore_npm_cache:
    steps:
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}

jobs:
  module-install:
    executor: default
    steps:
      - checkout
      - install_module
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          when: always
          paths:
            - ~/.npm

  lint:
    executor: default
    steps:
      - checkout
      - restore_npm_cache
      - install_module
      - run:
          name: lint
          command: npm run lint

  build:
    executor: default
    steps:
      - checkout
      - restore_npm_cache
      - install_module
      - run:
          name: build
          command: npm run build

  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: install utils
          command: npm install --global semver
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build and push
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              IMAGE_TAG="${CIRCLE_TAG:1}"
              latest=`cat <(curl -Ls https://registry.hub.docker.com/v1/repositories/trap/traq-ui/tags | jq -r '.[].name' | grep -E '^[0-9]+(\.[0-9]+){2}.*') <(echo $IMAGE_TAG) | xargs semver | tail -n 1`
              if [ "$IMAGE_TAG" = "$latest" ]; then
                NEW_RELEASE=1
              fi
            elif [ "$CIRCLE_BRANCH" = "master" ]; then
              IMAGE_TAG="latest"
            else
              IMAGE_TAG="$CIRCLE_BRANCH"
            fi
            docker build -t trap/traq-ui:$IMAGE_TAG .
            docker push trap/traq-ui:$IMAGE_TAG

            if [ "$NEW_RELEASE" = "1" ]; then
              docker tag trap/traq-ui:$IMAGE_TAG trap/traq-ui:release
              docker push trap/traq-ui:release
            fi


workflows:
  version: 2
  main:
    jobs:
      - module-install
      - lint:
          requires:
            - module-install
      - build:
          requires:
            - module-install
      - build-image:
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
